### PR TITLE
Add support for HTTP PATCH for body_data

### PR DESCRIPTION
**Pull request by SysPete**

### CODE REVIEW

**Comment by jjn1056** [comment]
@SysPete I'm sympathetic to the need for this but I think it might be unexpected to code in the wild (possible open vulnerabilities, not sure...) I'd prefer maybe we could take that bit of logic "return unless ($self->method eq 'POST' || $self->method eq 'PUT');" and turn it into a method call like maybe

return unless $self->request_has_body_data

and then request_has_body_data does like 

return unless $self->method IN $self->allowed_body_data_methods  (mock code here)

and then allowed_body_data_methods   is pulled from Catalyst configuration, with a default of the current behavior but they you could override it.

That would preserve existing code but let you customize.  I mean in theory even a GET could have a body content (although not commonly).  

Honestly this issue points out a major architectural defect but not much we can do at this point I guess :(

**Comment by jjn1056** [comment]
Hey,  just letting you know AFAIK there's nobody doing reviews / merges.

**Comment by jhannah** [comment]
Merged into `release-candidates/rc-5.90116`

**Comment by jjn1056** [comment]
merged into RC

**Pull request closed without merging**
