### PR TITLE
Test case for handle_unicode_encoding_exception

### PR DESCRIPTION
**Pull request by melmothx**
Same as PR 138 but against branch.

### CODE REVIEW

**Comment by melmothx** [comment]
perl-catalyst-sync <notifications@github.com> writes:

> Closed #139.

Closed without any comment or explanation?

-- 
Marco

**Comment by jjn1056** [comment]
I was actually looking for this yesterday when I cut a release.  Looks like the sync script from shadowgit blew it away some how.  I'll revive it

**Comment by jjn1056** [comment]
Ok so I created a new branch with discussion.  Here's a transcript from IRC.  Look it over and see what you think.

<@jnap> 
moltar: hey so I took another look at the issue you wrote a test case for
10:17 AM and I think after messing around with it that I can't reliably allow one to set a Catalyst response that way, doing any part of the prepare phase
10:18 AM because you don't know what's prepared or not :)
10:18 AM you can't be sure to set a response based on a properly prepared context for example
10:18 AM however you can use a HTTP style exception to raise a response reliably
10:19 AM since that stuff bypasses the normal Catalyst cycle.  
10:19 AM Its actually one of the only decent uses of the HTTP exception stuff, IMHO (some would probably say there's no good use for them...)
10:20 AM Here's a code example, moltar i checked into the repo under a branch: https://github.com/perl-catalyst/catalyst-runtime/blob/unicode-exception-issue/t/unicode-exception-bug.t
10:20 AM ⇐ xinming quit  •  abraxxa1 → abraxxa  

10:21 AM J<@jnap> 
since you have $c there, you could even call ->render on templates and all that.  Let me know if you think this solves your issue.  If so lets try to write a cookbook style entry for people after us
10:22 AM I'll leave the issue open for now, until we deem the approach suitable and have a documentation patch.

**Comment by melmothx** [comment]
I confirm that this approach works well. I will provide a doc patch.

**Pull request closed without merging**
