### PR TITLE
Added tests for (currently failing) type constraint controller actions

### PR DESCRIPTION
**Pull request by kaare**
- When using namespace::autoclean
 - When the acion is in a role

### CODE REVIEW

**Comment by jjn1056** [comment]
Pulled this in manually,

**Comment by jjn1056** [comment]
So I added code to allow one to use a full namespace like Arg(MyType::Int) which lets you get around the problem somewhat.  Its not an ideal workaround but does actually help. just FYI  that will be in 5.90099 when it comes out.

**Comment by kaare** [comment]
Hi John
>
> So I added code to allow one to use a full namespace like 
> Arg(MyType::Int) which lets you get around the problem somewhat. Its 
> not an ideal workaround but does actually help. just FYI that will be 
> in 5.90099 when it comes out.
>

Thanks, I greatly appreciate this. I did, however, use a workaround that 
works until a permanent solution perhaps will come sometime.

Keep up the good work.

/kaare

**Comment by jjn1056** [comment]
Hey so master HEAD I think has a fix for this issue.  I know you said you have a workaround but if you  had time to check out the code and see if its good for you I'd appreciate it.

**Comment by jjn1056** [comment]
I'm going to close this branch but feel free to reopen if you still have trouble thanks!

**Comment by kaare** [comment]
I hope I can get around to it sometime this or next week. Kinda busy...

Thanks again.

**Comment by kaare** [comment]
Hi

> I'm going to close this branch but feel free to reopen if you still 
> have trouble thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perl-catalyst/catalyst-runtime/pull/112#issuecomment-134233949>.
>

Just tested on master (5.90100) and it works as expected.

- I can use namespace::autoclean
- I can use Types::Standard in a role, used in a controller

**Pull request closed without merging**
