### PR TITLE
Adds test suite assuming orthogonality of query keywords/params

### PR DESCRIPTION
**Pull request by asparkman**
https://github.com/perl-catalyst/catalyst-runtime/issues/134

### CODE REVIEW

**Comment by asparkman** [comment]
I need to make sure that these changes actually apply to the population of body_parameters for a POST using the application/x-www-url-encoded Content-Type as well.

**Comment by jjn1056** [comment]
I can't say I see anything really wrong here but it also makes me nervous since it s a bigger change to a pretty core part of the request setup.  I don't think its worth the risk right now.  Will leave this active but needs more eyeballs.

**Comment by jjn1056** [comment]
Hey,  just letting you know AFAIK there's nobody doing reviews / merges.

**Comment by jhannah** [comment]
Merged into `release-candidates/rc-5.90116`

**Pull request closed without merging**
