### PR TITLE
Fixed :Path() empty brackets attribute not registering action.

### PR DESCRIPTION
**Pull request by grim8634**
Fixes: #104

### CODE REVIEW

**Comment by grim8634** [comment]
I'll take a look why this is failing in a bit. Cheers.

**Comment by perl-catalyst-sync** [comment]
Its probably failing because that regex is reused for a few different
things. :)

**Comment by jjn1056** [comment]
Hey I was just reviewing and am a bit worried here.  Not sure what the behavior change is (not sure what we might break in the wild).  Can you help me understand the fix?  for example if you did :Path() before the fix, how did the action get setup as compared to now?

I do think its great to nail down this (Idealing Path and Path() would be the same) but I don't want to bust stuff in the wild.  thanks!

**Comment by jjn1056** [comment]
doh, ok right https://github.com/perl-catalyst/catalyst-runtime/issues/104  let me think :)

**Pull request merged**
